version: "3.7"

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./dataBase/mysql.env
    container_name: mysql-container

  database:
    build:
      context: ./dataBase
    image: chat-data-base-image
    ports:
    - "8089:8089"
    container_name: chat-data-base-container

