version: "3.7"

services:

  mysqldb:
    image: mysql:latest
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=chat_db
    container_name: mysqldb-container
    restart: always
    networks:
      - bd-net

  appdb:
    build:
      context: ./dataBase
      dockerfile: Dockerfile
    image: chat-data-base-image
    ports:
    - 8089
    container_name: chat-data-base-container
    networks:
      - bd-net
    depends_on:
      - mysqldb
    links:
      - mysqldb

  parentapp:
    build:
      context: ./

networks:
  bd-net:
    driver: bridge
