version: "3.7"

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./dataBase/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=chat_db
      - MYSQL_USER=$
    container_name: mysql-container

  database:
    build:
      context: ./dataBase
    image: chat-data-base-image
    ports:
    - "8089:8089"
    container_name: chat-data-base-container
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql

